DO $$ 
BEGIN
 	IF EXISTS (
 		SELECT 1
 		FROM information_schema.routines
 		WHERE lower(routine_name) = lower('csiSetNextTxnId')
 		AND routine_type = 'PROCEDURE'
 	) then
 		DROP PROCEDURE IF EXISTS csiSetNextTxnId;
 	END IF;
END $$;

CREATE PROCEDURE csiSetNextTxnId(
	p_maxhexid varchar(15)
)
language plpgsql
as $$
DECLARE
	v_newmaxid	bigint;
	v_sqlstmt	varchar(1000);
BEGIN
	-- Calculate the new max ID
	call csihextodec(p_maxhexid, v_newmaxid);
    v_newmaxid := v_newmaxid + 1;

    -- Drop the column idVal if it exists
    PERFORM column_name
    FROM information_schema.columns
    WHERE table_name = 'transactionidtable' AND column_name = 'idval';
    
    IF FOUND THEN
        EXECUTE 'ALTER TABLE transactionidtable DROP COLUMN idval';
    END IF;

    -- Add the new column idVal with an identity
    v_sqlstmt := 'ALTER TABLE transactionidtable ADD COLUMN idVal BIGINT GENERATED BY DEFAULT AS IDENTITY (START ' || v_newmaxid || ')';
    EXECUTE v_sqlstmt;

    -- Drop the TRANSACTIONIDTABLERESETDATA Table if it exists
    BEGIN
        EXECUTE 'DROP TABLE IF EXISTS TRANSACTIONIDTABLERESETDATA';
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Error occurred while dropping table';
    END;
END;
$$;