Service:
  Account: User
  UserName: Camstaradmin
  Password: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAI9aCa4DD8EOKcWelF3a6qQAAAAACAAAAAAAQZgAAAAEAACAAAAA9KuBZAhvDgpFzCV1QK9Vj0JlufywUbvYMuSPfLYdpuAAAAAAOgAAAAAIAACAAAADuCNbAmqCt5dbzQOXxhVz4a0Z5o/G2nIb6yTZs1kteThAAAADXQAkAkfzSKc0I22zLOYlsQAAAANHAiqutalqz3WlDrHE1vaI2RA5wneclJ+Xqhd18V94JXWZvBYhqJYBEiBHIbu5/XEAn+7MQU+hQ1Uodz8BUXK0=
  ServiceName: Mendix Semiconductor App
  DisplayName: Mendix Semiconductor App
  Description: Mendix Semiconductor App
  StartMode: AUTOMATIC
Jetty: {}
Database:
  DatabaseType: SQLSERVER
  DatabaseHost: localhost
  DatabaseName: Mendix
  DatabaseUserName: Mendix_Login
  DatabasePassword: AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAOxMsZnKwAEK1Uv3ymB6YRAAAAAACAAAAAAAQZgAAAAEAACAAAABDmDf1D467pIvEIgQp0GcrCybi5iE54jvCaHusMjuGuQAAAAAOgAAAAAIAACAAAAClAjpvYUIfagzex7jfUmJkIVxFtCNv2luZHa9EWNQN7RAAAAD9WUTb+TYyw6aZ/aT2U2QZQAAAANNY62DZttmse/h/lHYRuwKPv8DlFmZzMOWeKkBzklYPezdMihYurtQKoZfnu+7qsTRrFG5D7OawX2F6EsZNghg=
  DatabaseUseIntegratedSecurity: False
QSlotId: '{cb1b7fb5-0f43-4521-a6a0-84cd5d093ae5}.{274f9918-d1d5-428a-9a27-6d173ec93d64}'
Version: 1.0.0
Runtime:
  MendixPath: C:\Program Files (x86)\Camstar\Mendix Solutions\Servers
  JavaPath: C:\Program Files\Microsoft\jdk-21.0.11.10-hotspot
  MaxJavaHeapSize: 1024
  RuntimePortNumber: 8080
  ServerPortNumber: 8090
  ServerPassword: nl@tRzyyFUUk0eygb3PyaCxmDovE)Nrp
  ApplicationRootUrl: https://localhost
  ScheduledEventExecution: ALL
  CACertificates: C:\Program Files (x86)\Camstar\Mendix Solutions\Apps\Mendix Semiconductor App\Project\OpcenterCert.cer
  DatabaseUseSsl: False
  http.client.MaxConnectionsPerRoute: 250
  http.client.MaxConnectionsTotal: 250
  com.mendix.core.SessionIdCookieName: SemiXASSESSIONID
Custom:
  CommunityCommons.MergeMultiplePdfs_MaxAtOnce: 10
  Core_Delta.core_delta_version: 0.0.1
  DocumentGeneration.AsyncTimeoutInSeconds: 300
  DocumentGeneration.CloudEndpoint: https://docgen.home.mendix.com
  DocumentGeneration.CustomChromePath: C:\Program Files\Google\Chrome\Application\chrome.exe
  DocumentGeneration.CustomNodePath: C:\Program Files\nodejs\node.exe
  DocumentGeneration.OverrideServiceType: Local
  DocumentGeneration.SyncTimeoutInSeconds: 30
  DocumentGeneration.TokenLifetimeInSeconds: 1800
  Encryption.EncryptionKey: xSSOEncryptKey01SSOEncryptKey01x
  Encryption.EncryptionPrefix: '{AES3}'
  Encryption.LegacyEncryptionKey: xSSOEncryptKey01SSOEncryptKey01x
  Encryption.LogNode: Encryption
  EXCR_Authentication.AdminUsername: Camstaradmin
  EXCR_Authentication.ContainerizationAuthServerUrl: ''
  EXCR_Authentication.ContainerizationCamstarPortalUrl: ''
  EXCR_Authentication.ContainerizationMendixPortalPodName: ''
  EXCR_Authentication.ContainerizationNamespaceName: ''
  EXCR_Authentication.ContainerizationRestApiFileServerLocation: ''
  EXCR_Authentication.EnableSSO: False
  EXCR_Authentication.IdPVerificationKey: OpcenterCore
  EXCR_Authentication.ServerTimezone: __utcoffset -05:00
  EXCR_Authentication.ServerURL: https://localhost
  EXCR_Commons.SuccessMessageFadeoutTime: 6000
  EXCR_ExtEntityAccess.EntityFactoryURL: http://localhost:8080
  EXCR_ResourceManagement.SignalRHubName: opcenterHub
  SAML20.BindingURI_Redirect: False
  SAML20.DefaultEntity: Administration.Account
  SAML20.DefaultLoginPage: ''
  SAML20.DefaultLogoutPage: index.html
  SAML20.DisableDecoding_Deeplink_URL: False
  SAML20.IdPAlias: ''
  SAML20.IdPMetadataURL: ''
  SAML20.KeystorePassword: R@nd0mP4$$w0rdFOrK3ySt0r3
  SAML20.Org_DisplayName: Test
  SAML20.Org_Emailaddress: Test@email.com
  SAML20.Org_GivenName: Test
  SAML20.Org_Name: Test Compay
  SAML20.Org_OrganizationURL: test.com
  SAML20.Org_Surname: Tester
  SAML20.SP_Entity: ''
  SAML20.SSOLandingPage: index.html
